---
title: "Research"
---

## Work in Progress

1. "Labor market concentration and employee childbearing", with Luis Cabral and Pedro S. Martins.
2. "Labor market concentration and firm productivity", with Luis Cabral and Pedro S. Martins.
3. "What is (behind) the gender gap in sickness leave? Evidence from two administrative datasets", with Judite Goncalves, Pedro S. Martins, Joao Rocha-Gomes, and Mario Amorim-Lopes.
4. "Is the future of work childless? Self-employment, contract type and fertility", with Judite Goncalves and Pedro S. Martins.
5. "Minimum wages and retention", with Jonathan Thomas, Andrew Snell, and Pedro S. Martins.
6. "The anatomy of private-sector strikes: firm predictors, worker participation, and economic consequences", with Pedro S. Martins.

## Policy Work

1. Martins, Pedro S., and Enzo Almeida. 2026. "Apoiar a natalidade: o papel do mercado de trabalho." S4P-23 Policy Brief 5596/2023. PLANAPP - Centro de Planeamento e de Avaliacao de Politicas Publicas.
2. Villanueva, Luis, and Enzo Almeida. 2024. "Employment Impact Assessment of the Mozambique-Malawi Interconnector Project." STRENGTHEN2 Project, International Labour Organization.
3. Villanueva, Luis, and Enzo Almeida. 2024. "Portfolio Assessment of Public Infrastructure Investments in the Southern Mediterranean: A Study of the Mainstreaming Employment into Trade and Investment in the Southern Mediterranean Programme." International Labour Organization. Unpublished.
4. Villanueva, Luis, and Enzo Almeida. 2024. "EmpIA Report: Global Gateway Sub-Saharan Africa Portfolio 2023." International Labour Organization. Unpublished.
